# Generated by Django 4.0.5 on 2022-07-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191115_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='pts',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
