# Generated by Django 4.0.5 on 2022-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_logininfo_pts'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
