# Generated by Django 4.0.5 on 2022-07-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_type_logininfo_passtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='sec_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
